### ISSUE TITLE
Relicense Descriptors Docker under ASL 2.0 ? 

### ISSUE THREAD

**Issue by aslakknutsen** [shrinkwrap/descriptors-docker#2]
Descriptors Docker is currently under EPL, should this be relicensed as ASL 2.0  to follow rest of ShrinkWrap Org; https://github.com/shrinkwrap/descriptors-docker/blob/master/pom.xml#L23

**Comment by aslakknutsen** [comment]
Oops.. Missed the code refs.

**Comment by gastaldi** [comment]
:+1: to relicense it
